#!/usr/bin/env python3
"""
Sandia Data Path Finder
Searches for pmCDEF folder and updates scripts with correct path
"""

import os
from pathlib import Path

print("=" * 80)
print("SANDIA DATA PATH FINDER")
print("=" * 80)

# ─────────────────────────────────────────────
# Search for pmCDEF folder
# ─────────────────────────────────────────────

print("\nSearching for pmCDEF folder...")
print("(This may take a moment...)")

possible_locations = [
    # Current directory and subdirectories
    Path.cwd() / "pmCDEF",
    Path.cwd() / "pmCDEF" / "pmD.stat",
    
    # Downloads folder
    Path.home() / "Downloads" / "pmCDEF",
    Path.home() / "Downloads" / "ShauryaMLModel" / "pmCDEF",
    Path.home() / "Downloads" / "pmCDEF" / "pmD.stat",
    
    # Desktop
    Path.home() / "Desktop" / "pmCDEF",
    Path.home() / "Desktop" / "pmCDEF" / "pmD.stat",
    
    # Documents
    Path.home() / "Documents" / "pmCDEF",
    Path.home() / "Documents" / "pmCDEF" / "pmD.stat",
]

found_path = None

print("\nChecking common locations:")
for loc in possible_locations:
    if loc.exists():
        print(f"  ✓ FOUND: {loc}")
        if "pmD.stat" in str(loc):
            found_path = loc.parent
        else:
            found_path = loc
        break
    else:
        print(f"  ✗ Not found: {loc}")

# If not found in common locations, search recursively
if not found_path:
    print("\nSearching entire Downloads folder...")
    downloads_dir = Path.home() / "Downloads"
    
    for root, dirs, files in os.walk(downloads_dir):
        if "pmD.stat" in dirs:
            found_path = Path(root) / "pmCDEF"
            print(f"  ✓ FOUND: {found_path}")
            break

if not found_path:
    print("\n❌ Cannot find pmCDEF folder!")
    print("\nPlease check:")
    print("  1. Did you download pmCDEF.zip?")
    print("  2. Did you extract it?")
    print("  3. Is it in your Downloads folder?")
    print("\nExpected path:")
    print(f"  C:\\Users\\{os.getenv('USERNAME')}\\Downloads\\ShauryaMLModel\\pmCDEF\\")
    print("\nOR")
    print(f"  C:\\Users\\{os.getenv('USERNAME')}\\Downloads\\pmCDEF\\")
    exit()

# ─────────────────────────────────────────────
# Verify structure
# ─────────────────────────────────────────────

print("\nVerifying folder structure...")

pmD_stat = found_path / "pmD.stat"
if not pmD_stat.exists():
    print(f"❌ ERROR: {pmD_stat} does not exist!")
    print(f"\nFound pmCDEF at: {found_path}")
    print(f"But pmD.stat subfolder is missing!")
    exit()

yave_files = list(pmD_stat.glob("D*.Yave"))
if not yave_files:
    print(f"❌ No D*.Yave files found in {pmD_stat}")
    exit()

print(f"  ✓ pmD.stat folder: {pmD_stat}")
print(f"  ✓ Number of .Yave files: {len(yave_files)}")

# ─────────────────────────────────────────────
# Display found path
# ─────────────────────────────────────────────

print("\n" + "=" * 80)
print("SANDIA DATA FOUND!")
print("=" * 80)

print(f"\nFull path: {pmD_stat.absolute()}")
print(f"\nFiles found:")
for f in sorted(yave_files)[:10]:
    print(f"  {f.name}")
if len(yave_files) > 10:
    print(f"  ... and {len(yave_files) - 10} more")

# ─────────────────────────────────────────────
# Create configuration file
# ─────────────────────────────────────────────

print("\n" + "=" * 80)
print("CREATING CONFIGURATION")
print("=" * 80)

config_content = f"""# Sandia Data Path Configuration
# Auto-generated by path_finder.py

SANDIA_PATH = r"{pmD_stat.absolute()}"
SANDIA_PARENT = r"{found_path.absolute()}"
NUM_YAVE_FILES = {len(yave_files)}
"""

config_file = "sandia_config.py"
with open(config_file, "w") as f:
    f.write(config_content)

print(f"\n✓ Created: {config_file}")
print("\nNow you can use this in your scripts:")
print("  from sandia_config import SANDIA_PATH")

# ─────────────────────────────────────────────
# Instructions
# ─────────────────────────────────────────────

print("\n" + "=" * 80)
print("NEXT STEPS")
print("=" * 80)

print(f"""
1. Run the parser (it will automatically use the found path):
   python3 sandia_yave_parser_FINAL.py

OR

2. Manually copy the path and update scripts:
   {pmD_stat.absolute()}

3. If you need to change the path later:
   Edit sandia_config.py

Your Sandia data is ready to process! 🚀
""")

print("=" * 80)
