# Sandia Data Path Configuration
# Auto-generated by path_finder.py

SANDIA_PATH = r"C:\Users\Ashish\Downloads\ShauryaMLModel\pmCDEF\pmD.stat"
SANDIA_PARENT = r"C:\Users\Ashish\Downloads\ShauryaMLModel\pmCDEF"
NUM_YAVE_FILES = 10
